global:
  tazamaVersion: "rc" # Overrides ${TAZAMA_VERSION} across all deployments
  imageRegistry: "docker.io/tazamaorg"
  storageClass: "longhorn-single" # Custom environment configuration from RKE2 deployment profile 

  # Base Infrastructure Hosts
  database:
    host: "postgres"
    user: "postgres"
    password: "unused" # Base infrastructure authentication profile 
  valkey:
    host: "valkey"
  nats:
    host: "nats"

infrastructure:
  postgres:
    image: "postgres:18" # Configured base target image 
    storageSize: "5Gi" # Right-sized persistent allocation 
  valkey:
    image: "valkey/valkey:7.2.5" # Base caching layer target image 
  nats:
    image: "nats:2" # Event transport image version 

core:
  adminService:
    port: 3100 # Internal execution target port 
  tms:
    port: 3000 # Transaction Monitoring target port
