apiVersion: apps/v1
kind: Deployment
metadata:
  name: nats
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nats
  template:
    metadata:
      labels:
        app: nats
    spec:
      containers:
        - name: nats
          image: "{{ .Values.infrastructure.nats.image }}"
          args: ["-DVV"]
          ports:
            - containerPort: 4222
              name: client
            - containerPort: 6222
              name: cluster
            - containerPort: 8222
              name: monitor
---
apiVersion: v1
kind: Service
metadata:
  name: nats-service
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - name: client
      port: 4222
      targetPort: 4222
    - name: cluster
      port: 6222
      targetPort: 6222
    - name: monitor
      port: 8222
      targetPort: 8222
  selector:
    app: nats
