apiVersion: v1
kind: ConfigMap
metadata:
  name: tazama-core-config
  namespace: {{ .Release.Namespace }}
data:
  NODE_ENV: "dev"
  LOG_LEVEL: "info"

  # Deactivate active APM tracing to stop the ENOTFOUND proxy noise
  APM_ACTIVE: "false"
  ELASTIC_APM_ACTIVE: "false"

  # Stream Router Configurations
  SERVER_URL: "nats:4222"
  
  # Cache Tier Configurations
  REDIS_SERVERS: '[{"host":"valkey", "port":6379}]'
  REDIS_IS_CLUSTER: "false"

  # Global Database Host Specifications 
  CONFIGURATION_DATABASE_HOST: "postgres"
  EVENT_HISTORY_DATABASE_HOST: "postgres"
  RAW_HISTORY_DATABASE_HOST: "postgres"
  EVALUATION_DATABASE_HOST: "postgres"

  # Required NATS Stream Routing Keys
  INTERDICTION_PRODUCER: "interdiction"
