apiVersion: v1
kind: ConfigMap
metadata:
  name: tazama-core-config
  namespace: {{ .Release.Namespace }}
data:
  NODE_ENV: "dev"
  LOG_LEVEL: "info"
  
  # Telemetry / APM Suppression Flags
  APM_ACTIVE: "false"
  ELASTIC_APM_ACTIVE: "false"

  # Infrastructure Network Coordinates
  SERVER_URL: "nats:4222"
  REDIS_SERVERS: '[{"host":"valkey", "port":6379}]'
  REDIS_IS_CLUSTER: "false"
  CONFIGURATION_DATABASE_HOST: "postgres"
  EVENT_HISTORY_DATABASE_HOST: "postgres"
  RAW_HISTORY_DATABASE_HOST: "postgres"
  EVALUATION_DATABASE_HOST: "postgres"

  # NATS Core Stream Message Routing Matrix
  INTERDICTION_PRODUCER: "interdiction"
  INTERDICTION_DESTINATION: "interdiction"
  ALERT_PRODUCER: "alert"
  ALERT_DESTINATION: "alert"
  SUPPRESS_ALERTS: "false"
