apiVersion: v1
kind: ConfigMap
metadata:
  name: tazama-core-config
  namespace: {{ .Release.Namespace }}
data:
  NODE_ENV: "dev" # Default environment classification 
  LOG_LEVEL: "info" # System logging visibility constraint [cite: 23, 25, 27]
  VALKEY_SERVERS: '[{"host":"valkey", "port":6379}]' # Runtime backend endpoints 
  NATS_SERVER_URL: "nats://nats:4222" # Global cluster messaging router [cite: 21, 23, 25]
