apiVersion: v1
kind: Secret
metadata:
  name: tazama-shared-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  CONFIGURATION_DATABASE_USER: {{ .Values.global.database.user | quote }}
  CONFIGURATION_DATABASE_PASSWORD: {{ .Values.global.database.password | quote }}
  EVENT_HISTORY_DATABASE_USER: {{ .Values.global.database.user | quote }}
  EVENT_HISTORY_DATABASE_PASSWORD: {{ .Values.global.database.password | quote }}
  EVALUATION_DATABASE_USER: {{ .Values.global.database.user | quote }}
  EVALUATION_DATABASE_PASSWORD: {{ .Values.global.database.password | quote }}
  RAW_HISTORY_DATABASE_USER: {{ .Values.global.database.user | quote }}
  RAW_HISTORY_DATABASE_PASSWORD: {{ .Values.global.database.password | quote }}
